version: "3.3"
services:
  app-test:
    image: python:36
    build: .
    network_mode: "host"
    env_file:
       - .env.test
    depends_on:
      - redis-test
  redis-test:
    image: "redis:alpine"
    command: --port 6380
    network_mode: "host"
